spring:
  datasource0:
   url: jdbc:mysql://192.168.18.128:3306/GOOD0?characterEncoding=utf8&useSSL=false
   userName: root
   passWord: root
   driverClassName: com.mysql.jdbc.Driver
   dataBasename: GOOD0
  datasource1:
   url: jdbc:mysql://192.168.18.129:3306/GOOD1?characterEncoding=utf8&useSSL=false
   userName: root
   passWord: root
   driverClassName: com.mysql.jdbc.Driver
   dataBasename: GOOD1
