datasource:
   names: db0,db1
   db0:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.18.128:3306/GOOD0?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
   db1:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.18.129:3306/GOOD1?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #分库策略  根据id取模
  sharding:
   default-database-strategy:
    inline:
     sharding-column: id
     algorithm-expression: ds$->{id % 2}
   #分表策略  根据id取模,确定数据最终落在哪个表中
   tables:
    t_order:
     actual-data-nodes: ds$->{0..1}.t_order_$->{0..2}
     table-strategy:
      inline:
       sharding-column: id
       algorithm-expression: t_order_$->{id % 3}
    key-generator:
     column: id
     type: SNOWFLAKE
   binding-tables: t_order
   masterslave:
    load-balance-algorithm-type: round_robin
    name: ms
   master-slave-rules:
    db0:
     master-data-source-name: db0
     slave-data-source-names: db1