dataSources:
  GOOD0: !!com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.18.128:3306/GOOD0?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  GOOD1: !!com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.18.129:3306/GOOD1?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
#  #分库策略  根据id取模
shardingRule:
  defaultDataSourceName: GOOD0
  defaultDatabaseStrategy:
    inline:
      shardingColumn: id
      algorithmExpression: GOOD${id % 2}
  #分表策略  根据id取模,确定数据最终落在哪个表中
  tables:
    t_order:
      actualDataNodes: GOOD${0..1}.t_order_${0..2}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: t_order_${id % 3}
      keyGeneratorColumnName: id
